INSERT INTO employee (id, version, firstName, lastName) VALUES (0, 0, 'admin', 'admin');
INSERT INTO employee (id, version, firstName, lastName) VALUES (1, 0, 'Moritz', 'Schulze');
INSERT INTO employee (id, version, firstName, lastName) VALUES (2, 0, 'Viktor', 'Widiker');
INSERT INTO employee (id, version, firstName, lastName) VALUES (3, 0, 'Alexander', 'Hanschke');
INSERT INTO employee (id, version, firstName, lastName) VALUES (4, 0, 'Adrian', 'Krion');
INSERT INTO employee (id, version, firstName, lastName) VALUES (5, 0, 'Angelika', 'Gutjahr');
INSERT INTO employee (id, version, firstName, lastName) VALUES (6, 0, 'Nikolaj', 'Weise');
INSERT INTO credential (id, email, enabled) VALUES (0, 'admin', true);
INSERT INTO credential (id, email, enabled) VALUES (1, 'moritz.schulze@techdev.de', true);
INSERT INTO credential (id, email, enabled) VALUES (2, 'viktor.widiker@techdev.de', true);
INSERT INTO credential (id, email, enabled) VALUES (3, 'alexander.hanschke@techdev.de', true);
INSERT INTO credential (id, email, enabled) VALUES (4, 'adrian.krion@techdev.de', true);
INSERT INTO credential (id, email, enabled) VALUES (5, 'angelika.gutjahr@techdev.de', true);
INSERT INTO credential (id, email, enabled) VALUES (6, 'nikolaj.weise@techdev.de', true);
INSERT INTO authority (id, authority, screenName, authorityOrder) VALUES (0, 'ROLE_ADMIN', 'Administrator', 0);
INSERT INTO authority (id, authority, screenName, authorityOrder) VALUES (1, 'ROLE_SUPERVISOR', 'Supervisor', 1);
INSERT INTO authority (id, authority, screenName, authorityOrder) VALUES (2, 'ROLE_EMPLOYEE', 'Angestellter', 2);
INSERT INTO credential_authority (credential_id, authorities_id) VALUES (0, 0);
INSERT INTO credential_authority (credential_id, authorities_id) VALUES (1, 0);
INSERT INTO credential_authority (credential_id, authorities_id) VALUES (2, 1);
INSERT INTO credential_authority (credential_id, authorities_id) VALUES (3, 1);
INSERT INTO credential_authority (credential_id, authorities_id) VALUES (4, 1);
INSERT INTO credential_authority (credential_id, authorities_id) VALUES (5, 1);
INSERT INTO credential_authority (credential_id, authorities_id) VALUES (6, 1);

INSERT INTO company (id, version, companyId, name, street, houseNumber, zipCode, city, country) VALUES (0, 0, 1000, 'techdev Solutions UG', 'Bismarckstraße', '47', '76133', 'Karlsruhe', 'Deutschland');
INSERT INTO company (id, version, companyId, name, street, houseNumber, zipCode, city, country) VALUES (1, 0, 1001, 'cofinpro AG', 'Zur Gießerei', '19a', '76123', 'Karlsruhe', 'Deutschland');
